=== usgin/metadataBuildingBlocks/_sources/cdifProperties/cdifMandatory/cdifMandatorySchema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "title": "Optional properties for CDIF Discovery metadata schema, with schema: prefixes",
    "description": "Building block specifies properties for minimal CDIF schama.org discovery record",
    "properties": {
        "@context": {
            "type": "object",
            "description": "JSON-LD context declaring namespace prefixes used in the metadata record.",
            "properties": {
                "schema": {
                    "const": "http://schema.org/"
                },
                "dcterms": {
                    "const": "http://purl.org/dc/terms/"
                },
                "spdx": {
                    "const": "http://spdx.org/rdf/terms#"
                },
                "dcat": {
                    "const": "http://www.w3.org/ns/dcat#"
                }
            },
            "required": [
                "schema",
                "dcterms"
            ]
        },
        "@id": {
            "type": "string",
            "description": "The URI for the resource should be the @id value for the root of the JSON instance document tree. Must be an IRI (e.g. https://doi.org/..., urn:..., or a relative URI like #localid). Note that this identifier can be interpreted to identify the resource that is the subject of this metadata record, or the JSON-LD object that is the digital object containing the metadata information."
        },
        "@type": {
            "description": "a schema.org Class that specifies the expected information content for the metadata record. The array must include at least one schema.org type value. Default is schema:Dataset.",
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "schema:CreativeWork",
                    "schema:SoftwareApplication",
                    "schema:SoftwareSourceCode",
                    "schema:Product",
                    "schema:WebAPI",
                    "schema:Dataset",
                    "schema:DigitalDocument",
                    "schema:Collection",
                    "schema:ImageObject",
                    "schema:DataCatalog",
                    "schema:DefinedTermSet",
                    "schema:MediaObject"
                ]
            },
            "default": "schema:Dataset",
            "minItems": 1,
            "contains": {
                "const": "schema:Dataset"
            }
        },
        "schema:name": {
            "type": "string",
            "description": "A descriptive name of a dataset (e.g., 'Snow depth in Northern Hemisphere'). The name should uniquely identify the described resource for human use, in the scope of the metadata catalog containing this metadata record."
        },
        "schema:identifier": {
            "description": "The primary identifier for the dataset; other identifiers should be listed in the sameAs field. Schema.org has three ways of encoding identifiers-- a text description, a URL, or by using the schema:PropertyValue field. The Science on Schema.org guidance strongly recommends using the PropertyValue approach. see https://github.com/ESIPFed/science-on-schema.org   .... Dataset.md#identifier.  Ideally, for any given data provided they would provide identifiers either all as strings or all as identifier_type.",
            "anyOf": [
                {
                    "$ref": "#/$defs/Identifier"
                },
                {
                    "type": "string"
                }
            ]
        },
        "schema:dateModified": {
            "type": "string",
            "description": "ISO8601 formatted date (and optional time if relevant) when Dataset was last updated"
        },
        "schema:conditionsOfAccess": {
            "description": "text statement of conditions for use and access; if an online resource documents the restrictions or a URI is used to identify the conditions, recommend using schema:CreativeWork to provide a label (name) and an identifier (URI or URL). ",
            "type": "array",
            "minItems": 0,
            "items": {
                "anyOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "description": "a reference to a resource defining conditions of Access"
                            }
                        }
                    },
                    {
                        "$ref": "#/$defs/LabeledLink"
                    }
                ]
            }
        },
        "schema:license": {
            "description": "legal statement of conditions for use and access; recommend using schema:CreativeWork to provide a label (name) for the license, and an identifier. Sources of license identifiers: https://opensource.org/licenses/, https://creativecommons.org/about/cclicenses/, https://spdx.org/licenses/, http://cor.esipfed.org/ont/earthcube/swl. If only a string is provided, it should be an identifier for the license, ideally a resolvable URI",
            "type": "array",
            "minItems": 0,
            "items": {
                "anyOf": [
                    {
                        "type": "string"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "@id": {
                                "type": "string",
                                "description": "a reference to a license defintion"
                            }
                        }
                    },
                    {
                        "$ref": "#/$defs/LabeledLink"
                    }
                ]
            }
        },
        "schema:url": {
            "type": "string",
            "format": "uri",
            "description": "Web Location of a page describing the dataset (landing page), typically providing links or instructions to get the actual resource content; analogous to dcat:accessURL. If a direct link is available to get the data, put in distribution/contentUrl"
        },
        "schema:distribution": {
            "description": "specifies how to download the data in a specific format or access via a web API. This property describes where to get the data and in what format by using the schema:DataDownload type. If user must access data through a landing page, provide link to landing page in the 'url' property for the dataset",
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/$defs/DataDownload"
                    },
                    {
                        "$ref": "#/$defs/WebAPI"
                    }
                ]
            }
        },
        "schema:subjectOf": {
            "$ref": "#/$defs/CdifCatalogRecord"
        }
    },
    "allOf": [
        {
            "required": [
                "@id",
                "@type",
                "@context",
                "schema:name",
                "schema:identifier",
                "schema:dateModified",
                "schema:subjectOf"
            ]
        },
        {
            "anyOf": [
                {
                    "required": [
                        "schema:license"
                    ]
                },
                {
                    "required": [
                        "schema:conditionsOfAccess"
                    ]
                }
            ]
        },
        {
            "anyOf": [
                {
                    "required": [
                        "schema:url"
                    ]
                },
                {
                    "required": [
                        "schema:distribution"
                    ]
                }
            ]
        }
    ],
    "$defs": {
        "LabeledLink": {
            "$ref": "../../schemaorgProperties/labeledLink/labeledLinkSchema.json"
        },
        "Identifier": {
            "$ref": "../../schemaorgProperties/identifier/identifierSchema.json"
        },
        "DefinedTerm": {
            "$ref": "../../schemaorgProperties/definedTerm/definedTermSchema.json"
        },
        "DataDownload": {
            "$ref": "../../schemaorgProperties/dataDownload/dataDownloadSchema.json"
        },
        "WebAPI": {
            "$ref": "../../schemaorgProperties/webAPI/webAPISchema.json"
        },
        "CdifCatalogRecord": {
            "$ref": "../cdifCatalogRecord/cdifCatalogRecordSchema.json"
        }
    }
}

=== usgin/metadataBuildingBlocks/_sources/cdifProperties/cdifMandatory/exampleCdifMandatory.json
{
    "@context": {
        "schema": "http://schema.org/",
        "ex": "https://example.org/",
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "dcterms": "http://purl.org/dc/terms/",
        "dcat": "http://www.w3.org/ns/dcat#"
    },
    "@id": "ex:baseDiscovery23578",
    "@type": [
        "schema:Dataset"
    ],
    "schema:name": "Bathymetry Bay of Biscay",
    "schema:identifier": "https://doi.org/23566/aslry",
    "schema:url": "https://example.org/landingPage254266",
    "schema:dateModified": "2022-12-12",
    "schema:license": [
        "https://creativecommons.org/publicdomain/zero/1.0/"
    ],
    "schema:subjectOf": {
        "@type": [
            "schema:Dataset"
        ],
        "schema:additionalType": [
            "dcat:CatalogRecord"
        ],
        "@id": "ex:URIforMetadata3575",
        "schema:about": {
            "@id": "ex:baseDiscovery23578"
        },
        "dcterms:conformsTo": [
            {
                "@id": "https://w3id.org/cdif/bbr/metadata/cdifProperties/cdifMandatory"
            },
            {
                "@id": "https://w3id.org/cdif/core/1.0/"
            }
        ],
        "schema:maintainer": {
            "@id": "https://orcid.org/3333-4442-9456-9347",
            "@type": "schema:Person",
            "schema:name": "Goodge, Alice",
            "schema:alternateName": "Metadata curator",
            "schema:contactPoint": {
                "@id": "ex:aContactPoint",
                "@type": "schema:ContactPoint",
                "schema:email": "goodgea@bwc.org"
            },
            "schema:identifier": {
                "@id": "ex:maintainerIdentifier",
                "@type": "schema:PropertyValue",
                "schema:propertyID": "https://registry.identifiers.org/registry/orcid",
                "schema:url": "https://orcid.org/3333-4442-9456-9347"
            }
        },
        "schema:sdDatePublished": "2025-10-24",
        "schema:includedInDataCatalog": {
            "@id": "https://ror.org/04sfkyrt24",
            "@type": "schema:DataCatalog",
            "schema:name": "Global Wildlife Aggregator",
            "schema:url": "http://example.com/wildlifecatalog"
        }
    }
}
